module.exports = {
    connectDb: require("./dbConnection"),
    employeeModel: require("./models/Employee"),
    userModel: require("./models/User"),
    adminModel: require("./models/Admin"),
    SubjecthModel: require("./models/Subject"),
    CourseModel: require("./models/Course"),
    BatchModel: require("./models/Batch"),
    StudentModel: require("./models/Student"),
    QpOutlineModel: require("./models/QpOutline"),
    PSeriesModel: require("./models/prelimsSeries"),
    mSeriesModel: require("./models/mainsSeries"),
    pQpDesModel: require("./models/PrelimsQpDesc"),
    psQuestionModel: require("./models/PrelimsQuestion"),
    pSalesModel: require("./models/prelimsSales"),
    mQpDesModel: require("./models/MainsQpDesc"),
    mSalesModel: require("./models/mainsSales"),
    attemptModel: require("./models/Attempt"),
    mAttemptModel: require("./models/mainsAttempt"),
    pResultModel: require("./models/prelimResult"),
    mResultModel: require("./models/mainResult"),
};